# Generated by Django 2.0.4 on 2018-04-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
