# Generated by Django 2.0.4 on 2018-04-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Summary', '0002_auto_20180425_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=50)),
                ('summary', models.TextField(max_length=100)),
                ('file', models.FileField(upload_to='data/')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
