# Generated by Django 2.0.4 on 2018-04-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0003_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='summary',
        ),
        migrations.AddField(
            model_name='documents',
            name='keywords',
            field=models.TextField(default='', max_length=100),
        ),
    ]
