# Generated by Django 2.0.4 on 2018-04-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0004_auto_20180426_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(upload_to='./Summary/data/'),
        ),
    ]
