# Generated by Django 2.0.4 on 2018-04-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0005_auto_20180427_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documents',
            name='size',
            field=models.FloatField(default=0.0),
        ),
    ]
