# Generated by Django 2.0.4 on 2018-04-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0006_auto_20180430_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='upload_user',
            field=models.CharField(default='未知', max_length=20),
        ),
    ]
