# Generated by Django 2.0.4 on 2018-04-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0007_documents_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='type',
            field=models.CharField(default='未知', max_length=100),
        ),
    ]
