# Generated by Django 2.0.4 on 2018-04-30 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0008_documents_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='documents',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='documents',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
