# Generated by Django 2.0.4 on 2018-04-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0009_auto_20180430_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
