# Generated by Django 2.0.4 on 2018-04-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0010_auto_20180430_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
