# Generated by Django 2.0.4 on 2018-05-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0011_auto_20180430_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='type',
            field=models.CharField(default='未知', max_length=20),
        ),
    ]
